[package]
name = "CRYPI_project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.1"
ndarray = "0.15.6"
serde = { version = "1.0.130", features = ["derive"] }
ciphercore-base = "0.2.0"
serde_json = "1.0.96"